/* GENERATED — triage queue snapshot. Regenerate with `python -m kvcomp.serialize --queue`. */
window.QUEUE = [
  {
    "id": "KV-1063",
    "address": "107 TARARIDGE CL NE",
    "district": "North East",
    "rangeLow": 545500,
    "rangePoint": 550000,
    "rangeHigh": 554500,
    "confidenceBand": "HIGH",
    "verdict": "red",
    "reason": "Raw (pre-adjustment) price spread 40% exceeds the 30% watch.",
    "reviewFlagCount": 4,
    "score": 0.8559
  },
  {
    "id": "KV-1062",
    "address": "5437 VALENTINE CR SE",
    "district": "East",
    "rangeLow": 488500,
    "rangePoint": 492500,
    "rangeHigh": 496500,
    "confidenceBand": "HIGH",
    "verdict": "red",
    "reason": "Raw (pre-adjustment) price spread 39% exceeds the 30% watch.",
    "reviewFlagCount": 3,
    "score": 0.8391
  },
  {
    "id": "KV-1061",
    "address": "83 LAKE WAPTA RI SE",
    "district": "South",
    "rangeLow": 713000,
    "rangePoint": 718500,
    "rangeHigh": 724000,
    "confidenceBand": "LIMITED",
    "verdict": "red",
    "reason": "2 comps selected — below the minimum of 4.",
    "reviewFlagCount": 2,
    "score": 0.5266
  },
  {
    "id": "KV-1051",
    "address": "100 MT DOUGLAS PT SE",
    "district": "South East",
    "rangeLow": 703000,
    "rangePoint": 708500,
    "rangeHigh": 714000,
    "confidenceBand": "MODERATE",
    "verdict": "yellow",
    "reason": "Comp set required tier-2 relaxation to reach the minimum count; recency distribution degraded, confidence penalised -0.10. · COMP-E exceed the 120-day recency watch; time-adjusted off the CREB benchmark, weight reduced.",
    "reviewFlagCount": 3,
    "score": 0.7665
  },
  {
    "id": "KV-1055",
    "address": "52 PANORAMA HILLS GR NW",
    "district": "North",
    "rangeLow": 640000,
    "rangePoint": 645500,
    "rangeHigh": 651000,
    "confidenceBand": "MODERATE",
    "verdict": "yellow",
    "reason": "Comp set required tier-2 relaxation to reach the minimum count; recency distribution degraded, confidence penalised -0.10. · COMP-E exceed the 120-day recency watch; time-adjusted off the CREB benchmark, weight reduced.",
    "reviewFlagCount": 3,
    "score": 0.7986
  },
  {
    "id": "KV-1052",
    "address": "42 PANORAMA HILLS GR NW",
    "district": "North",
    "rangeLow": 639500,
    "rangePoint": 649000,
    "rangeHigh": 658500,
    "confidenceBand": "HIGH",
    "verdict": "yellow",
    "reason": "COMP-E 13.5% exceed the 12% review band (hard cap 25%); retained at reduced weight. · COMP-A -9.1%, COMP-B -9.3%, COMP-C -9.6%, COMP-D -10.5%, COMP-E -10.3% exceed the 8% net review band; narrative support advised.",
    "reviewFlagCount": 3,
    "score": 0.8175
  },
  {
    "id": "KV-1054",
    "address": "6 CRANSTON PL SE",
    "district": "South East",
    "rangeLow": 694500,
    "rangePoint": 700500,
    "rangeHigh": 706500,
    "confidenceBand": "HIGH",
    "verdict": "yellow",
    "reason": "COMP-E 12.6% exceed the 12% review band (hard cap 25%); retained at reduced weight. · COMP-A -8.6%, COMP-B -8.6%, COMP-C -8.9%, COMP-D -9.8%, COMP-E -9.3% exceed the 8% net review band; narrative support advised.",
    "reviewFlagCount": 3,
    "score": 0.8534
  },
  {
    "id": "KV-1053",
    "address": "808 SADDLECREEK WY NE",
    "district": "North East",
    "rangeLow": 566000,
    "rangePoint": 570500,
    "rangeHigh": 575000,
    "confidenceBand": "HIGH",
    "verdict": "yellow",
    "reason": "COMP-A, COMP-B use the city-wide fallback series (no encoded district benchmark); time adjustment is approximate.",
    "reviewFlagCount": 1,
    "score": 0.8186
  },
  {
    "id": "KV-1043",
    "address": "6924 15 AV SE",
    "district": "East",
    "rangeLow": 491000,
    "rangePoint": 497500,
    "rangeHigh": 504000,
    "confidenceBand": "HIGH",
    "verdict": "green",
    "reason": "HIGH; no review flags",
    "reviewFlagCount": 0,
    "score": 0.8869
  },
  {
    "id": "KV-1045",
    "address": "6920 15 AV SE",
    "district": "East",
    "rangeLow": 489000,
    "rangePoint": 493000,
    "rangeHigh": 497000,
    "confidenceBand": "HIGH",
    "verdict": "green",
    "reason": "HIGH; no review flags",
    "reviewFlagCount": 0,
    "score": 0.9117
  },
  {
    "id": "KV-1044",
    "address": "75 LAKE WAPTA RI SE",
    "district": "South",
    "rangeLow": 740500,
    "rangePoint": 747000,
    "rangeHigh": 753500,
    "confidenceBand": "HIGH",
    "verdict": "green",
    "reason": "HIGH; no review flags",
    "reviewFlagCount": 0,
    "score": 0.9128
  },
  {
    "id": "KV-1042",
    "address": "79 LAKE WAPTA RI SE",
    "district": "South",
    "rangeLow": 718500,
    "rangePoint": 724500,
    "rangeHigh": 730500,
    "confidenceBand": "HIGH",
    "verdict": "green",
    "reason": "HIGH; no review flags",
    "reviewFlagCount": 0,
    "score": 0.9145
  }
];
