/* GENERATED — triage queue snapshot. Regenerate with `python -m kvcomp.serialize --queue`. */
window.QUEUE = [
  {
    "id": "KV-1063",
    "address": "107 TARARIDGE CL NE",
    "district": "North East",
    "rangeLow": 488500,
    "rangePoint": 492500,
    "rangeHigh": 496500,
    "confidenceBand": "HIGH",
    "verdict": "red",
    "reason": "Raw (pre-adjustment) price spread 45% exceeds the 30% watch.",
    "reviewFlagCount": 4,
    "score": 0.8438
  },
  {
    "id": "KV-1062",
    "address": "5437 VALENTINE CR SE",
    "district": "East",
    "rangeLow": 471500,
    "rangePoint": 475500,
    "rangeHigh": 479500,
    "confidenceBand": "HIGH",
    "verdict": "red",
    "reason": "Raw (pre-adjustment) price spread 40% exceeds the 30% watch.",
    "reviewFlagCount": 3,
    "score": 0.8376
  },
  {
    "id": "KV-1061",
    "address": "83 LAKE WAPTA RI SE",
    "district": "South",
    "rangeLow": 910000,
    "rangePoint": 917500,
    "rangeHigh": 925000,
    "confidenceBand": "MODERATE",
    "verdict": "red",
    "reason": "3 comps selected — below the minimum of 4.",
    "reviewFlagCount": 2,
    "score": 0.6127
  },
  {
    "id": "KV-1051",
    "address": "100 MT DOUGLAS PT SE",
    "district": "South East",
    "rangeLow": 814000,
    "rangePoint": 820500,
    "rangeHigh": 827000,
    "confidenceBand": "MODERATE",
    "verdict": "yellow",
    "reason": "Comp set required tier-2 relaxation to reach the minimum count; recency distribution degraded, confidence penalised -0.10. · COMP-E exceed the 120-day recency watch; time-adjusted off the CREB benchmark, weight reduced.",
    "reviewFlagCount": 3,
    "score": 0.7669
  },
  {
    "id": "KV-1052",
    "address": "42 PANORAMA HILLS GR NW",
    "district": "North",
    "rangeLow": 715000,
    "rangePoint": 725000,
    "rangeHigh": 735000,
    "confidenceBand": "MODERATE",
    "verdict": "yellow",
    "reason": "COMP-E 12.3% exceed the 12% review band (hard cap 25%); retained at reduced weight. · COMP-B -8.4%, COMP-C -8.6%, COMP-D -9.4%, COMP-E -9.1% exceed the 8% net review band; narrative support advised.",
    "reviewFlagCount": 3,
    "score": 0.7925
  },
  {
    "id": "KV-1055",
    "address": "52 PANORAMA HILLS GR NW",
    "district": "North",
    "rangeLow": 723500,
    "rangePoint": 730000,
    "rangeHigh": 736500,
    "confidenceBand": "MODERATE",
    "verdict": "yellow",
    "reason": "Comp set required tier-2 relaxation to reach the minimum count; recency distribution degraded, confidence penalised -0.10. · COMP-E exceed the 120-day recency watch; time-adjusted off the CREB benchmark, weight reduced.",
    "reviewFlagCount": 3,
    "score": 0.7976
  },
  {
    "id": "KV-1054",
    "address": "6 CRANSTON PL SE",
    "district": "South East",
    "rangeLow": 741500,
    "rangePoint": 748000,
    "rangeHigh": 754500,
    "confidenceBand": "HIGH",
    "verdict": "yellow",
    "reason": "COMP-A -8.1%, COMP-B -8.1%, COMP-C -8.4%, COMP-D -9.2%, COMP-E -8.7% exceed the 8% net review band; narrative support advised. · COMP-A, COMP-B, COMP-C, COMP-D, COMP-E use the city-wide fallback series (no encoded district benchmark); time adjustment is approximate.",
    "reviewFlagCount": 2,
    "score": 0.8565
  },
  {
    "id": "KV-1053",
    "address": "808 SADDLECREEK WY NE",
    "district": "North East",
    "rangeLow": 667500,
    "rangePoint": 673000,
    "rangeHigh": 678500,
    "confidenceBand": "HIGH",
    "verdict": "yellow",
    "reason": "COMP-A, COMP-B use the city-wide fallback series (no encoded district benchmark); time adjustment is approximate.",
    "reviewFlagCount": 1,
    "score": 0.8184
  },
  {
    "id": "KV-1043",
    "address": "6924 15 AV SE",
    "district": "East",
    "rangeLow": 482000,
    "rangePoint": 488500,
    "rangeHigh": 495000,
    "confidenceBand": "HIGH",
    "verdict": "green",
    "reason": "HIGH; no review flags",
    "reviewFlagCount": 0,
    "score": 0.8855
  },
  {
    "id": "KV-1045",
    "address": "6920 15 AV SE",
    "district": "East",
    "rangeLow": 474500,
    "rangePoint": 478500,
    "rangeHigh": 482500,
    "confidenceBand": "HIGH",
    "verdict": "green",
    "reason": "HIGH; no review flags",
    "reviewFlagCount": 0,
    "score": 0.9101
  },
  {
    "id": "KV-1044",
    "address": "75 LAKE WAPTA RI SE",
    "district": "South",
    "rangeLow": 898000,
    "rangePoint": 906000,
    "rangeHigh": 914000,
    "confidenceBand": "HIGH",
    "verdict": "green",
    "reason": "HIGH; no review flags",
    "reviewFlagCount": 0,
    "score": 0.9133
  },
  {
    "id": "KV-1042",
    "address": "79 LAKE WAPTA RI SE",
    "district": "South",
    "rangeLow": 799000,
    "rangePoint": 805500,
    "rangeHigh": 812000,
    "confidenceBand": "HIGH",
    "verdict": "green",
    "reason": "HIGH; no review flags",
    "reviewFlagCount": 0,
    "score": 0.9165
  }
];
