/* GENERATED — triage queue snapshot. Regenerate with `python -m kvcomp.serialize --queue`. */
window.QUEUE = [
  {
    "id": "KV-1063",
    "address": "51xx Rundlehorn Drive NE",
    "district": "North East",
    "rangeLow": 547000,
    "rangePoint": 551500,
    "rangeHigh": 556000,
    "confidenceBand": "HIGH",
    "verdict": "red",
    "reason": "Raw (pre-adjustment) price spread 40% exceeds the 30% watch.",
    "reviewFlagCount": 4,
    "score": 0.8585
  },
  {
    "id": "KV-1062",
    "address": "3xx Penworth Road SE",
    "district": "East",
    "rangeLow": 498000,
    "rangePoint": 502000,
    "rangeHigh": 506000,
    "confidenceBand": "HIGH",
    "verdict": "red",
    "reason": "Raw (pre-adjustment) price spread 39% exceeds the 30% watch.",
    "reviewFlagCount": 3,
    "score": 0.8485
  },
  {
    "id": "KV-1061",
    "address": "61xx Maple Ridge Drive SE",
    "district": "South",
    "rangeLow": 721000,
    "rangePoint": 727000,
    "rangeHigh": 733000,
    "confidenceBand": "MODERATE",
    "verdict": "red",
    "reason": "3 comps selected — below the minimum of 4.",
    "reviewFlagCount": 2,
    "score": 0.6115
  },
  {
    "id": "KV-1051",
    "address": "14xx Lake Sylvan Drive SE",
    "district": "South East",
    "rangeLow": 687000,
    "rangePoint": 692500,
    "rangeHigh": 698000,
    "confidenceBand": "MODERATE",
    "verdict": "yellow",
    "reason": "Comp set required tier-2 relaxation to reach the minimum count; recency distribution degraded, confidence penalised -0.10. · COMP-E exceed the 120-day recency watch; time-adjusted off the CREB benchmark, weight reduced.",
    "reviewFlagCount": 3,
    "score": 0.7654
  },
  {
    "id": "KV-1055",
    "address": "15xx 7th Street NE",
    "district": "North",
    "rangeLow": 632500,
    "rangePoint": 638000,
    "rangeHigh": 643500,
    "confidenceBand": "MODERATE",
    "verdict": "yellow",
    "reason": "Comp set required tier-2 relaxation to reach the minimum count; recency distribution degraded, confidence penalised -0.10. · COMP-E exceed the 120-day recency watch; time-adjusted off the CREB benchmark, weight reduced.",
    "reviewFlagCount": 3,
    "score": 0.798
  },
  {
    "id": "KV-1052",
    "address": "52xx 4th Street NE",
    "district": "North",
    "rangeLow": 641500,
    "rangePoint": 651000,
    "rangeHigh": 660500,
    "confidenceBand": "HIGH",
    "verdict": "yellow",
    "reason": "COMP-E 13.5% exceed the 12% review band (hard cap 25%); retained at reduced weight. · COMP-A -9.1%, COMP-B -9.3%, COMP-C -9.6%, COMP-D -10.4%, COMP-E -10.2% exceed the 8% net review band; narrative support advised.",
    "reviewFlagCount": 3,
    "score": 0.8179
  },
  {
    "id": "KV-1054",
    "address": "92xx Auburn Bay Avenue SE",
    "district": "South East",
    "rangeLow": 699500,
    "rangePoint": 705500,
    "rangeHigh": 711500,
    "confidenceBand": "HIGH",
    "verdict": "yellow",
    "reason": "COMP-E 12.5% exceed the 12% review band (hard cap 25%); retained at reduced weight. · COMP-A -8.5%, COMP-B -8.6%, COMP-C -8.9%, COMP-D -9.7%, COMP-E -9.3% exceed the 8% net review band; narrative support advised.",
    "reviewFlagCount": 3,
    "score": 0.8541
  },
  {
    "id": "KV-1053",
    "address": "38xx Marbank Drive NE",
    "district": "North East",
    "rangeLow": 556000,
    "rangePoint": 560500,
    "rangeHigh": 565000,
    "confidenceBand": "HIGH",
    "verdict": "yellow",
    "reason": "COMP-A, COMP-B use the city-wide fallback series (no encoded district benchmark); time adjustment is approximate.",
    "reviewFlagCount": 1,
    "score": 0.8177
  },
  {
    "id": "KV-1042",
    "address": "84xx Bonaventure Drive SE",
    "district": "South",
    "rangeLow": 710000,
    "rangePoint": 715500,
    "rangeHigh": 721000,
    "confidenceBand": "HIGH",
    "verdict": "green",
    "reason": "HIGH; no review flags",
    "reviewFlagCount": 0,
    "score": 0.8803
  },
  {
    "id": "KV-1043",
    "address": "9xx Penbrooke Road SE",
    "district": "East",
    "rangeLow": 493000,
    "rangePoint": 499500,
    "rangeHigh": 506000,
    "confidenceBand": "HIGH",
    "verdict": "green",
    "reason": "HIGH; no review flags",
    "reviewFlagCount": 0,
    "score": 0.8872
  },
  {
    "id": "KV-1045",
    "address": "74xx 21A Street SE",
    "district": "East",
    "rangeLow": 483000,
    "rangePoint": 487000,
    "rangeHigh": 491000,
    "confidenceBand": "HIGH",
    "verdict": "green",
    "reason": "HIGH; no review flags",
    "reviewFlagCount": 0,
    "score": 0.9111
  },
  {
    "id": "KV-1044",
    "address": "51xx Lake Bonavista Drive SE",
    "district": "South",
    "rangeLow": 725000,
    "rangePoint": 731500,
    "rangeHigh": 738000,
    "confidenceBand": "HIGH",
    "verdict": "green",
    "reason": "HIGH; no review flags",
    "reviewFlagCount": 0,
    "score": 0.9116
  }
];
