/* Section 6 — MEMO (full audit-ready document) */
function MemoSection() {
  const s = M.subject;
  const r = M.range;
  const cf = M.confidence;
  const n = M.narrative;
  const fired = M.flags.filter((f) => f.status === "FIRED");
  return (
    <section className="section" data-screen-label="Memo">
      <SectionTitle
        index="06"
        name="Comparable Sales Memo"
        sub="The complete, self-contained record an underwriter can file and defend in review — subject, comparables, grid summary, range, confidence, and flags, with narrative rationale."
        meta={<React.Fragment><Badge tone="ghost">case {M.meta.caseId}</Badge><Badge tone="ghost">effective {M.meta.effectiveDate}</Badge><SyntheticTag /></React.Fragment>}
      />

      <div className="memo-doc">
        <div className="memo-band">
          <div>
            <h2 className="memo-h">Sales-Comparison Comp Memo</h2>
            <div className="mono" style={{ fontSize: 12, color: "var(--muted)", marginTop: 6 }}>
              {s.addr} · {s.community}, {s.district} · Calgary AB
            </div>
            <div className="mono" style={{ fontSize: 11.5, color: "var(--faint)", marginTop: 3 }}>
              {M.meta.approach} · case {M.meta.caseId} · effective {M.meta.effectiveDate}
            </div>
          </div>
          <div className="status-strip">
            <div className="chip"><span className="chip-k">Range</span><span className="chip-v accent">{M.usd0(r.low)}–{M.usd0(r.high)}</span></div>
            <div className="chip"><span className="chip-k">Point</span><span className="chip-v">{M.usd0(r.point)}</span></div>
            <div className="chip"><span className="chip-k">Confidence</span><span className="chip-v warn">{cf.band} {cf.score.toFixed(2)}</span></div>
            <div className="chip"><span className="chip-k">Flags</span><span className="chip-v warn">{fired.length} fired</span></div>
          </div>
        </div>

        <div className="memo-sec">
          <h4>1 · Scope & subject</h4>
          <div className="llm-note">◴ narrative generated by model:underwrite-copilot · placeholder rationale</div>
          <div className="memo-prose"><p>{n.scope}</p></div>
          <div style={{ marginTop: 14 }} className="grid-2">
            <table className="tbl">
              <tbody>
                <tr><td className="k">Subject</td><td className="v">{s.addr}</td></tr>
                <tr><td className="k">GLA / lot</td><td className="v mono">1,450 sf / 5,242 sf</td></tr>
                <tr><td className="k">Beds / baths</td><td className="v mono">3 / 2F · 1H</td></tr>
                <tr><td className="k">Built · cond · qual</td><td className="v mono">1984 · C3 · Q3</td></tr>
              </tbody>
            </table>
            <table className="tbl">
              <tbody>
                <tr><td className="k">Assessed value</td><td className="v mono">{M.usd0(s.assessedValue)}</td></tr>
                <tr><td className="k">Provenance</td><td className="v mono" style={{ color: "var(--accent-2)" }}>{s.provenance}</td></tr>
                <tr><td className="k">South benchmark</td><td className="v mono">{M.usd0(M.marketContext.southBenchmark)}</td></tr>
                <tr><td className="k">Effective date</td><td className="v mono">{M.meta.effectiveDate}</td></tr>
              </tbody>
            </table>
          </div>
        </div>

        <div className="memo-sec">
          <h4>2 · Comparable selection</h4>
          <div className="memo-prose"><p>{n.selection}</p></div>
          <table className="tbl" style={{ marginTop: 12 }}>
            <thead>
              <tr><th>Comp</th><th>Price</th><th>GLA</th><th>Contract</th><th>Dist.</th><th>Tier</th><th>Adjusted</th><th>Status</th></tr>
            </thead>
            <tbody>
              {M.selected.map((c) => (
                <tr key={c.id}>
                  <td className="v mono" style={{ fontWeight: 600 }}>{c.label}</td>
                  <td className="mono">{M.usd0(c.price)}</td>
                  <td className="mono">{c.gla.toLocaleString()} sf</td>
                  <td className="mono">{c.contractDate}</td>
                  <td className="mono">{c.distanceKm} km</td>
                  <td className="mono">T{c.tier}</td>
                  <td className="mono v">{M.usd0(c.adjusted)}</td>
                  <td>{c.watch ? <Badge tone="warn">{c.watch[0]}</Badge> : <Badge tone="good">clean</Badge>}</td>
                </tr>
              ))}
              {M.rejected.map((c) => (
                <tr key={c.id} style={{ opacity: 0.7 }}>
                  <td className="mono" style={{ color: "var(--muted)" }}>{c.label}</td>
                  <td className="mono">{M.usd0(c.price)}</td>
                  <td className="mono">{c.gla.toLocaleString()} sf</td>
                  <td className="mono">{c.contractDate}</td>
                  <td className="mono">—</td>
                  <td className="mono">—</td>
                  <td className="mono" style={{ color: "var(--faint)" }}>rejected</td>
                  <td><span className="reason-code" style={{ fontSize: 10 }}>{c.code}</span></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="memo-sec">
          <h4>3 · Adjustment & reconciliation</h4>
          <div className="memo-prose"><p>{n.adjustment}</p><p>{n.reconciliation}</p></div>
          <div className="stat-row" style={{ marginTop: 14 }}>
            <Stat label="Range low" value={M.usd0(r.low)} />
            <Stat label="Weighted point" value={M.usd0(r.point)} tone="accent" />
            <Stat label="Range high" value={M.usd0(r.high)} />
            <Stat label="Spread" value={"±" + (r.spreadPct / 2).toFixed(1) + "%"} sub="of point" />
          </div>
        </div>

        <div className="memo-sec">
          <h4>4 · Confidence & flags</h4>
          <div className="memo-prose"><p>{n.confidence}</p></div>
          <div style={{ marginTop: 12, display: "flex", flexWrap: "wrap", gap: 8 }}>
            {fired.map((f) => (
              <span key={f.code} className="badge badge-warn" title={f.detail}>{f.code}</span>
            ))}
          </div>
          <div className="callout warn" style={{ marginTop: 14 }}>{M.aicNote}</div>
        </div>

        <div className="memo-sec">
          <h4>5 · Limiting conditions</h4>
          <div className="memo-prose"><p>{n.limiting}</p></div>
          <div className="note-line mono" style={{ marginTop: 12 }}>
            snapshot {M.meta.snapshot} · {M.meta.analyst} · render-only artifact, no live computation
          </div>
        </div>
      </div>
    </section>
  );
}
window.MemoSection = MemoSection;
